---

env:
    GOPATH: "/var/tmp/go"
    CIRRUS_WORKING_DIR: "${GOPATH}/src/github.com/containers/dnsname"
    GOSRC: "$CIRRUS_WORKING_DIR"
    CIRRUS_SHELL: "/bin/bash"
    IMAGE_PROJECT: "libpod-218412"
    HOME: "/root"  # not set by default
    GOCACHE: "${GOPATH}/cache"

    # Make names more readable in github/cirrus-ci
    FEDORA_NAME: "fedora-38"
    DEBIAN_NAME: "debian-12"

    # VM Images are maintained in the automation_images repo.
    IMAGE_SUFFIX: "c20230816t191118z-f38f37d13"
    FEDORA_CACHE_IMAGE_NAME: "fedora-${IMAGE_SUFFIX}"
    DEBIAN_CACHE_IMAGE_NAME: "debian-${IMAGE_SUFFIX}"

    # Must be defined true when testing w/in containers
    CONTAINER: "false"

gcp_credentials: ENCRYPTED[5ad247acfd6cfca94554b973d61a98a7882dfafbfcc1deb5faee8634cb3f8cf29720c88c243586d2975dd40885279db6]


# Default VM to use unless set or modified by task
gce_instance:
    image_project: "${IMAGE_PROJECT}"
    zone: "us-central1-c"  # Required by Cirrus for the time being
    cpu: 2
    memory: "4Gb"
    disk: 200  # Required for performance reasons
    image_name: "${FEDORA_CACHE_IMAGE_NAME}"


# Update metadata on VM images referenced by this repository state
meta_task:
    # see bors.toml
    skip: $CIRRUS_BRANCH =~ ".*\.tmp"

    container:
        image: "quay.io/libpod/imgts:latest"
        cpu: 1
        memory: 1

    env:
        CONTAINER: true
        # Space-separated list of images used by this repository state
        IMGNAMES: |-
            ${FEDORA_CACHE_IMAGE_NAME}
            ${DEBIAN_CACHE_IMAGE_NAME}
        BUILDID: "${CIRRUS_BUILD_ID}"
        REPOREF: "${CIRRUS_REPO_NAME}"
        GCPJSON: ENCRYPTED[35f6dca7928a3b676c05e0e6a6ce7f4ca3d347803e23b8d5d57ea8a22973248e2808e8726b9463b00b57e576c5ff0331]
        GCPNAME: ENCRYPTED[f3890da8c780aaa352ae8d1e3c9fedffd0a233625c1b983e6754e609a92d5c814167ee53ef967896d66c73710c90465e]
        GCPPROJECT: ENCRYPTED[e82537cfb95d6121717be1f23078a18b14de224de82ed2f72c0a8f0adc77b5c7e8ad394d10714214bccb9f010d65ac29]
        CIRRUS_CLONE_DEPTH: 1  # source not used

    script: /usr/local/bin/entrypoint.sh


validate_task:

    validate_script:
      - export PATH="$PATH:$GOPATH/bin"
      - make validate
      - make vendor
      - ./hack/tree_status.sh
      - make


test_task:
    alias: test

    depends_on:
        - validate

    matrix:
        - name: $FEDORA_NAME
          gce_instance:
            image_name: ${FEDORA_CACHE_IMAGE_NAME}
        - name: $DEBIAN_NAME
          gce_instance:
            image_name: ${DEBIAN_CACHE_IMAGE_NAME}

    test_script:
        - export PATH="$PATH:$GOPATH/bin"
        - make
        - make test
